name: Validate
on: 
  workflow_dispatch:
  pull_request:
  
jobs:
  validate:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2

    - name: Validate
      run: .\build\vsts-validate.ps1
      shell: pwsh
      
  del_runs:
    runs-on: ubuntu-latest
    steps:
    - name: Delete workflow runs
      if: always()
      uses: Mattraks/delete-workflow-runs@v2
      with:
        token: ${{ github.token }}
        repository: ${{ github.repository }}
        retain_days: 2
        keep_minimum_runs: 2
        delete_workflow_by_state_pattern: "All"
